@startuml

title Pigeon-swarm

package "shared" {
  package "domain" {
    class Key extends StringValueObject{}
    class Hash extends StringValueObject{}
    class identityId extends Hash {}
    class MessageId extends Hash {}
    class GroupId extends Hash {}
    class BoardId extends Hash {}
    class NodeId extends Hash {}
    class Address extends StringValueObject {}
    class Media {}
    class Image extends Media{}
    class Message {
      -id: MessageId
      -senderId: identityId
      -timestamp: Timestamp
      -payload?: StringValueObject
      -media: List<Media>
    }
    class EncryptedMessage extends Message{
      -publicKey: Key
    }

    Message *--> MessageId
    Message *--> identityId
    Media *--> Hash
    EncryptedMessage *--> Key
  }
}

package "profiles" {
   package "domain" {

    class Profile {
      -id: identityId
      -name: StringValueObject
      -biography: StringValueObject
      -profilePicture: StringValueObject
      -timestamp: Timestamp
      -signature: Hash
    }

    note left of Profile
      Profiles are optional public data of an Identity,
      signed by the Identity's private key.

      They can be updated without changing the
      Identity, but they need to be signed by the Identity

      This information is published publically,
      so it can be used by other users to display information about the Identity
      and makes an identity publicly through a searcher.
    end note

    class ProfileRepositoryService {}

    interface ProfileRepository {
      +save(profile: Profile): void
      +findById(identityId: identityId): Profile
    }
    ProfileRepositoryService ..> ProfileRepository
    ProfileRepositoryService --> Profile
  }

   package "application" {
    class ProfileGetter {
      +getProfile(identityId: identityId): Profile
    }
    class ProfileQRGenerator {
      +generateQR(identityId: identityId): Image
    }
    class ProfileProfilePictureUpdater {
      +updateProfilePicture(identityId: identityId, profilePicture: StringValueObject): void
    }
    class ProfileBiographyUpdater {
      +updateBiography(identityId: identityId, biography: StringValueObject): void
    }
  }

  ProfileGetter ..> ProfileRepositoryService
  ProfileQRGenerator ..> ProfileRepositoryService  
  ProfileProfilePictureUpdater ..> ProfileRepositoryService
  ProfileBiographyUpdater ..> ProfileRepositoryService
}

package "identities" {
  package "domain" {

    class Identity {
      -id: identityId
      -publicKey: Key
      -privateEncryptedKey: Key
      -signature: Hash
    }

    note left of Identity
      privateEncryptedKey = AES(password_derived_key, private_key)
      
      generate random private key
      encrypt private key with password↓
      store encrypted key

      Login:
        password
        derive key (argon2)
        decrypt private_key

      signature = sign(private_key, profile_data)
    end note

    class IdentityRepositoryService {}

    note left of IdentityRepositoryService
      Ideally, multiple services for different actions, Solid and KISS.
      To be able to update an Identity, we need to:
        -get profile by id
        -check signature
        -update fields
        -save Identity
    end note

    interface IdentityRepository {
      +save(Identity: Identity): void
      +findById(identityId: identityId): Identity
    }
    

    IdentityRepositoryService ..> IdentityRepository
    IdentityRepositoryService --> Identity

  }

  package "application" {
    class IdentityGetter {
      +getIdentity(identityId: identityId): Identity
    }
    class IdentityPasswordUpdater {
      +updatePassword(identityId: identityId, newPassword: String): void
    }
    class IdentityQRGenerator {
      +generateQR(identityId: identityId): Image
    }
  }

    IdentityGetter ..> IdentityRepositoryService
    IdentityPasswordUpdater ..> IdentityRepositoryService
    IdentityQRGenerator ..> IdentityRepositoryService  
}

package "contactLists" {
  package "domain" {
    class ContactList {
      -id: identityId
      -contacts: List<identityId>
    }

    note left of ContactList
      ContactList is a list of contacts of an Identity, 
      this should be encrypted with the Identity's private key
    end note
  }
}

package "nodes" {
  package "domain" {
    abstract class Node {
      -id: NodeId
      -ownerId: identityId
      -name: String
      -description: String
      -publicAddress: Address
      -publicKey: Key
    }

    class Peer extends Node {
      -lastSeen: Timestamp
    }

    class LocalNode extends Node {
      -peers: List<Peer>
      -privateKey: Key
    }

    LocalNode --> Peer
  }
}

package "conversations" {
  package "domain" {

    class Conversation {
      -id: GroupId
      -participants: List<UserId>
    }
  }
  note left of Conversation
   TODO: Add EncryptedMessages
   TODO: Voicechat and videochat? Which keys?
  end note
}

package "groups" {
  package "domain" {

    class Group {
      -id: GroupId
      -participants: List<UserId>
      -name: StringValueObject
      -isEncrypted: Boolean
      -privateKey?: Key
      -publicKey?: Key
    }
  }
  note left of Group
   TODO: Add EncryptedMessages
   TODO: All groups should be encrypted?
   TODO: How users know private keys?
   TODO: Voicechat and videochat?
  end note
}

package "boards" {
  package "domain" {

    class Board {
      -id: GroupId
      -name: StringValueObject
    }
  }
  note left of Board
  Boards are public by default. Anyone can join and see the content.
  There's no need to use an identity for the participants. Can be anonymous user.
  TODO: How to categorize boards? Maybe with tags?
  end note
}

@enduml