version: "3.9"

networks:
  local-net:
    external: false
    name: local-net

volumes:
  mongodata:

services:
  backend:
    container_name: "pigeon_swarm"
    build:
      target: local
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/dist
      - /var/www/var
    depends_on:
      amqp:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - local-net

  mongodb:
    image: mongo:7
    container_name: "pigeon_swarm_mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - local-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 30s
      retries: 3

  amqp:
    image: rabbitmq:3-management
    container_name: "pigeon_swarm_amqp"
    ports:
      - "5007:5672"
      - "15007:15672"
    networks:
      - local-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3
