services:
  backend:
    container_name: "pigeon_swarm"
    build:
      target: local
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/dist
      - /var/www/var
