services:
  backend:
    container_name: "pigeon_swarm"
    build:
      target: local
      context: .
    ports:
      - "8080:8080"
      - "4181:4181"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/dist
      - /var/www/var
    env_file:
      - .env.local
    environment:
      NODE_ENV: local
      PIGEON_LOCAL_DB_PATH: /var/www/local_storage
