openapi: 3.0.3
info:
  title: Pigeon-swarm APIs
  version: 1.0.0
  description: Aggregated OpenAPI document built with references to each API file.
tags:
  - name: example
  - name: identities
  - name: ipfs
paths:
  /identities/:
    $ref: './identities-api/swagger.yaml#/paths/~1identities~1'
  /ipfs/{cid}:
    $ref: './ipfs-api/swagger.yaml#/paths/~1ipfs~1{cid}'
