export const communityModerationActions = {
  CHANNEL_CREATED: 'channel_created',
  CHANNEL_DELETED: 'channel_deleted',
  CHANNEL_PERMISSIONS_UPDATED: 'channel_permissions_updated',
  CHANNEL_RENAMED: 'channel_renamed',
  COMMUNITY_UPDATED: 'community_updated',
  INVITATION_CREATED: 'invitation_created',
  INVITE_LINK_CREATED: 'invite_link_created',
  MEMBER_BANNED: 'member_banned',
  MEMBER_ROLES_UPDATED: 'member_roles_updated',
  MEMBER_UNBANNED: 'member_unbanned',
  MEMBERSHIP_REQUEST_ACCEPTED: 'membership_request_accepted',
  MEMBERSHIP_REQUEST_DECLINED: 'membership_request_declined',
  MESSAGE_DELETED: 'message_deleted',
  ROLE_CREATED: 'role_created',
  ROLE_DELETED: 'role_deleted',
  ROLE_UPDATED: 'role_updated',
} as const;
