@startuml

title Pigeon-swarm

package "identities" {
  package "domain" {

    class Identity <AggregateRoot> {
      -id: identityId
      -publicKey: Key
      -privateEncryptedKey: Key
      -timestamp: Timestamp
      -signature: Hash
    }

     class Profile {
      -name: StringValueObject
      -biography?: StringValueObject
      -profilePicture?: Image
    }

    class IdentityRepositoryService {}

    note left of IdentityRepositoryService
      Ideally, multiple services for different actions, Solid and KISS.
      To be able to update an Identity, we need to:
        -get profile by id
        -check signature
        -update fields
        -save Identity
    end note

    interface IdentityRepository {
      +save(Identity: Identity): void
      +findById(identityId: identityId): Identity
    }
    interface CryptoService {
      +encrypt(data: String, key: Key): String
      +decrypt(data: String, key: Key): String
      +validate(data: String, key: Key): String
    }


    Identity ..> CryptoService
    Identity *--> Profile
    IdentityRepositoryService ..> IdentityRepository
    IdentityRepositoryService o--> Identity

  }

  package "application" {
    class IdentityFinder {
      +findById(identityId: identityId): Identity
    }
    class IdentityCreator {
      +createIdentity(identity: Identity): void
    }
    class IdentityPasswordUpdater {
      +updatePassword(identityId: identityId, newPassword: String): void
    }

    note right of IdentityPasswordUpdater
      It s should be updated by backend or frontend?
    end note
  }

    IdentityFinder ..> IdentityRepositoryService
    IdentityCreator ..> IdentityRepositoryService
    IdentityPasswordUpdater ..> IdentityRepositoryService
}


@enduml
