@startuml

title Pigeon Swarm - Identities Context

package "identities" {
  package "domain" {

    class Identity <AggregateRoot> {
      -id: IdentityId
      -encryptedKeyPair: EncryptedKeyPair
      -networks: UniqueObjectArray<NetworkId>
      -profile: Profile
      -timestamp: Timestamp
      -signature: Signature
      +create(name, password): Identity
      +addNetwork(networkId): void
    }

    class Profile {
      -name: ProfileName
      -biography?: ProfileBiography
      -picture?: ProfileImage
    }

    class ProfileName {
    }

    class ProfileBiography {
    }

    class ProfileImage {
    }

    ' Domain Services
    class IdentitySignatureDomainService {
      +generate(identity): Signature
      +validate(identity): boolean
    }

    class IdentitySaverService {
      +save(identity): Promise<void>
    }

    class IdentityFinderService {
      +findById(identityId): Promise<Identity>
    }

    ' Repository
    interface IdentityRepository {
      +save(identity: Identity): Promise<void>
      +findById(id: IdentityId): Promise<Identity>
    }

    ' Relationships in domain
    Identity *--> Profile : contains
    Profile *--> ProfileName
    Profile *--> ProfileBiography
    Profile *--> ProfileImage
    Identity ..> IdentitySignatureDomainService
    IdentitySaverService --> Identity
    IdentitySaverService --> IdentityRepository
    IdentityFinderService --> IdentityRepository

  }

  package "application" {
    ' Use Cases
    class IdentityCreator {
      -saverService: IdentitySaverService
      +create(message: IdentityCreateMessage): Promise<Identity>
    }

    class IdentityFinder {
      -finderService: IdentityFinderService
      +find(message: IdentityFinderMessage): Promise<Identity>
    }
  }

  IdentityCreator --> IdentitySaverService
  IdentityFinder --> IdentityFinderService
}



@enduml
