@startuml ContentReplicationClasses
title content replication context

skinparam packageStyle rectangle
skinparam linetype ortho

package "content-replication/domain" {
  class ContentReplication <<AggregateRoot>>
  class ContentReplicaClaim <<Entity>>
  class ContentReplicationPolicy <<DomainService>>
  class ContentReplicationStatusSummary <<ReadModel>>

  interface ContentReplicationRepository
  interface ContentReplicationStatusSummaryRepository

  class ContentReplicationWasRegisteredEvent <<DomainEvent>>
  class ContentReplicationWasClaimedEvent <<DomainEvent>>
}

package "content-replication/application" {
  class ContentReplicationRegistrar
  class ContentReplicationMetadataRegistrar
  class ContentReplicaClaimRegistrar
  class ContentReplicationMaintainer
  class ContentReplicationStatusFinder
  class ContentReplicationStatus
  class ReplicatedContentStatus
  class NetworkReplicationStatus
  class ContentReplicationStatusSummaryFinder
  class ContentReplicationSummaryRefresher
  class ContentReplicationStatusSummaryUpdater
  class ContentReplicationMaintenanceResult
  class ContentNetworkReplicationStatus
}

package "content-replication/infrastructure" {
  class OrbitDBContentReplicationRepository
  class LocalContentReplicationStatusSummaryRepository
  class LocalContentReplicationStatusSummaryDocument
}

ContentReplication *-- ContentReplicaClaim
ContentReplicationPolicy ..> ContentReplication

ContentReplication ..> ContentReplicationWasRegisteredEvent
ContentReplication ..> ContentReplicationWasClaimedEvent

ContentReplicationRegistrar ..> ContentReplicationRepository
ContentReplicationMetadataRegistrar ..> ContentReplicationRepository
ContentReplicaClaimRegistrar ..> ContentReplicationRepository
ContentReplicationMaintainer ..> ContentReplicationPolicy
ContentReplicationMaintainer ..> ContentReplicationRepository
ContentReplicationStatusFinder ..> ContentReplicationRepository
ContentReplicationStatusFinder ..> ContentReplicationStatus
ContentReplicationStatus *-- ReplicatedContentStatus
ReplicatedContentStatus *-- NetworkReplicationStatus
ContentReplicationStatusSummaryFinder ..> ContentReplicationStatusSummaryRepository
ContentReplicationSummaryRefresher ..> ContentReplicationStatusSummaryRepository
ContentReplicationStatusSummaryUpdater ..> ContentReplicationStatusSummaryRepository
ContentReplicationMaintainer ..> ContentReplicationMaintenanceResult
ContentReplicationMaintainer ..> ContentNetworkReplicationStatus

OrbitDBContentReplicationRepository ..|> ContentReplicationRepository
LocalContentReplicationStatusSummaryRepository ..|> ContentReplicationStatusSummaryRepository
LocalContentReplicationStatusSummaryRepository ..> LocalContentReplicationStatusSummaryDocument

@enduml
