@startuml

title Pigeon-swarm

package "shared" {
  package "domain" {
    class Key extends StringValueObject{}
    class Hash extends StringValueObject{}
    class identityId extends PublicKey {}
    class MessageId extends Hash {}
    class GroupId extends Hash {}
    class BoardId extends Hash {}
    class NodeId extends UUID {}
    class NetworkId extends UUID {}
    class Address extends StringValueObject {}
    class Media {}
    class Image extends Media{}
    class Message {
      -id: MessageId
      -senderId: identityId
      -timestamp: Timestamp
      -media: List<Media>
      -text?: StringValueObject
    }

    Message *--> MessageId
    Message *--> identityId
    Media *--> Hash
    Message o--> Media
  }
}

package "KeyRing" {
  package "domain" {
    class KeyRing {
      -id: identityId
      -contacts: List<identityId>
      -conversations: Record<conversationId, Key?>
      -Signature: Hash
    }

    note left of KeyRing
      ContactList is a list of contacts of an Identity,
      this should be encrypted with the Identity's private key
    end note
  }

  package "application" {
    class ConversationKeySaver {
      +saveConversationKey(conversationId: conversationId, key: Key): void
    }
  }
}

package "conversations" {
  package "domain" {

    abstract class Conversation <AggregateRoot>{
      -id: ConversationId
      -participants: List<IdentityId>
    }

    class OneToOneConversation extends Conversation {
    }

    class GroupConversation extends Conversation {
       -publicKey: Key
    }

    note left of OneToOneConversation
      Limited to 2 participants, hast to be encrypted
      with both users exchanging public keys.
    end note

    class ConversationRepositoryService {}

    interface ConversationRepository {
      +save(Conversation: Conversation): void
      +findById(ConversationId: ConversationId): Conversation
      +remove(ConversationId: ConversationId): void
    }

    Conversation o--> Message
    ConversationRepositoryService ..> ConversationRepository
    ConversationRepositoryService o--> Conversation
  }

  package "application" {
    class ConversationFinder {
      +findById(conversationId: ConversationId): Conversation
    }
    class ConversationCreator {
      +createConversation(participants: List<identityId>): Conversation
    }
    class ConversationRemover {
      +removeConversation(conversationId: ConversationId): void
    }
  }

    ConversationFinder ..> ConversationRepositoryService
    ConversationCreator ..> ConversationRepositoryService
    ConversationRemover ..> ConversationRepositoryService
}

package "communities" {
  package "domain" {

    class Community {
      -id: GroupId
      -name: StringValueObject
      -isEncrypted: Boolean
      -privateKey?: Key
      -publicKey?: Key
    }
  }
  note left of Community
   TODO: Add EncryptedMessages
   TODO: All communities should be encrypted?
   TODO: How users know private keys?
   TODO: Voicechat and videochat?
   TODO: It has channels?
  end note
}

package "boards" {
  package "domain" {

    class Board {
      -id: GroupId
      -name: StringValueObject
    }
  }
  note left of Board
  Boards are public by default. Anyone can join and see the content.
  There's no need to use an identity for the participants. Can be anonymous user.
  TODO: How to categorize boards? Maybe with tags?
  end note
}

@enduml
