@startuml

title Pigeon-swarm

package "shared" {
  package "domain" {
    class Key extends StringValueObject{}
    class Hash extends StringValueObject{}
    class identityId extends Hash {}
    class MessageId extends Hash {}
    class GroupId extends Hash {}
    class BoardId extends Hash {}
    class NodeId extends Hash {}
    class Address extends StringValueObject {}
    class Media {}
    class Image extends Media{}
    class Message {
      -id: MessageId
      -senderId: identityId
      -timestamp: Timestamp
      -media: List<Media>
      -text?: StringValueObject
    }

    Message *--> MessageId
    Message *--> identityId
    Media *--> Hash
    Message o--> Media
  }
}

package "identities" {
  package "domain" {

    class Identity {
      -id: identityId
      -publicKey: Key
      -privateEncryptedKey: Key
      -timestamp: Timestamp
      -signature: Hash
    }

    note left of Identity
      privateEncryptedKey = AES(password_derived_key, private_key)

      generate random private key
      encrypt private key with password↓
      store encrypted key

      Login:
        password
        derive key (argon2)
        decrypt private_key

      signature = sign(private_key, profile_data)
    end note

     class Profile {
      -name: StringValueObject
      -biography?: StringValueObject
      -profilePicture?: Image
    }

    class IdentityRepositoryService {}

    note left of IdentityRepositoryService
      Ideally, multiple services for different actions, Solid and KISS.
      To be able to update an Identity, we need to:
        -get profile by id
        -check signature
        -update fields
        -save Identity
    end note

    interface IdentityRepository {
      +save(Identity: Identity): void
      +findById(identityId: identityId): Identity
    }
    interface CryptoService {
      +encrypt(data: String, key: Key): String
      +decrypt(data: String, key: Key): String
      +validate(data: String, key: Key): String
    }


    Identity ..> CryptoService
    Identity *--> Profile
    IdentityRepositoryService ..> IdentityRepository
    IdentityRepositoryService o--> Identity

  }

  package "application" {
    class IdentityFinder {
      +findById(identityId: identityId): Identity
    }
    class IdentityCreator {
      +createIdentity(identity: Identity): void
    }
    class IdentityPasswordUpdater {
      +updatePassword(identityId: identityId, newPassword: String): void
    }
    class IdentityQRGenerator {
      +generateQR(identityId: identityId): Image
    }
  }

    IdentityFinder ..> IdentityRepositoryService
    IdentityCreator ..> IdentityRepositoryService
    IdentityPasswordUpdater ..> IdentityRepositoryService
    IdentityQRGenerator ..> IdentityRepositoryService
}

package "KeyRing" {
  package "domain" {
    class KeyRing {
      -id: identityId
      -contacts: List<identityId>
      -conversations: Record<conversationId, Key?>
      -Signature: Hash
    }

    note left of KeyRing
      ContactList is a list of contacts of an Identity,
      this should be encrypted with the Identity's private key
    end note
  }

  package "application" {
    class ConversationKeySaver {
      +saveConversationKey(conversationId: conversationId, key: Key): void
    }
  }
}

package "nodes" {
  package "domain" {
    abstract class Node {
      -id: NodeId
      -ownerId: identityId
      -name: String
      -publicAddress: Address
      -publicKey: Key
      -signature: Hash
    }

    class Peer extends Node {
      -lastSeen: Timestamp
      -thrustScore: Int
    }

    class LocalNode extends Node {
      -peers: List<Peer>
      -privateKey: Key
      -peerWhitelist: List<Peer>
      -peerBlacklist: List<Peer>
      -identityWhitelist: List<identityId>
      -identityBlacklist: List<identityId>
    }

    LocalNode --> Peer
  }
}

package "conversations" {
  package "domain" {

    abstract class Conversation {
      -id: ConversationId
      -participants: List<UserId>
    }

    class OneToOneConversation extends Conversation {
    }

    class GroupConversation extends Conversation {
       -publicKey: Key
    }

    note left of OneToOneConversation
      Limited to 2 participants, hast to be encrypted
      with both users exchanging public keys.
    end note

    class ConversationRepositoryService {}

    interface ConversationRepository {
      +save(Conversation: Conversation): void
      +findById(ConversationId: ConversationId): Conversation
      +remove(ConversationId: ConversationId): void
    }

    Conversation o--> Message
    ConversationRepositoryService ..> ConversationRepository
    ConversationRepositoryService o--> Conversation
  }

  package "application" {
    class ConversationFinder {
      +findById(conversationId: ConversationId): Conversation
    }
    class ConversationCreator {
      +createConversation(participants: List<identityId>): Conversation
    }
    class ConversationRemover {
      +removeConversation(conversationId: ConversationId): void
    }
  }

    ConversationFinder ..> ConversationRepositoryService
    ConversationCreator ..> ConversationRepositoryService
    ConversationRemover ..> ConversationRepositoryService
}

package "communities" {
  package "domain" {

    class Community {
      -id: GroupId
      -name: StringValueObject
      -isEncrypted: Boolean
      -privateKey?: Key
      -publicKey?: Key
    }
  }
  note left of Community
   TODO: Add EncryptedMessages
   TODO: All communities should be encrypted?
   TODO: How users know private keys?
   TODO: Voicechat and videochat?
   TODO: It has channels?
  end note
}

package "boards" {
  package "domain" {

    class Board {
      -id: GroupId
      -name: StringValueObject
    }
  }
  note left of Board
  Boards are public by default. Anyone can join and see the content.
  There's no need to use an identity for the participants. Can be anonymous user.
  TODO: How to categorize boards? Maybe with tags?
  end note
}

@enduml
