@startuml

actor User

participant "Web UI"
participant "SendMessage"
participant "Encrypt"
participant "CRDT Log"
participant "IPFS"
participant "GossipSub"
participant "Remote Peer"

User -> "Web UI" : Login
"Web UI" -> "IPFS" : Retrieve User Identity
"IPFS" -> "Web UI" : Return (or not) user identity

"Web UI" -> "User" : Ask for password

User -> "Web UI" : Give password

"Web UI" -> "Web UI" : Decrypt private key

User -> "Web UI" : Send message

"Web UI" -> "SendMessage" : Send message

"SendMessage" -> "Encrypt" : encrypt payload

"Encrypt" --> "SendMessage" : ciphertext

"SendMessage" -> "CRDT Log" : append entry

"CRDT Log" -> "IPFS" : store entry object

"CRDT Log" --> "SendMessage" : new HEAD CID

"SendMessage" -> "GossipSub" : broadcast HEAD

"GossipSub" -> "Remote Peer" : HEAD CID

"Remote Peer" -> "IPFS" : fetch missing entries

@enduml
