export type OrbitDBReplicatedDocumentStoreName =
  | 'calls'
  | 'communityOperations'
  | 'conversationOperations'
  | 'identities'
  | 'contentReplication'
  | 'keychains'
  | 'messages'
  | 'moderationLogs'
  | 'notificationSettings'
  | 'notifications'
  | 'pins'
  | 'polls'
  | 'reactions'
  | 'requests'
  | 'stickerPacks'
  | 'stickerUserLibraries';
